# Generated by Django 5.0.2 on 2024-03-16 23:19

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(blank=True, verbose_name='Артикул')),
                ('qr_code', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('name', models.CharField(blank=True, max_length=175, verbose_name='Название')),
                ('quantity', models.IntegerField(blank=True, verbose_name='Количество')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_purchasing', models.IntegerField(blank=True, verbose_name='Цена закупочная')),
                ('price_retail', models.IntegerField(blank=True, verbose_name='Цена розница')),
                ('price_wholesale', models.IntegerField(blank=True, verbose_name='Цена оптовая')),
                ('price_agent', models.IntegerField(blank=True, verbose_name='Цена cвоим')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=main.models.product_photo_save, verbose_name='Фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.products')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('size', models.CharField(blank=True, max_length=30, verbose_name='Размер')),
                ('quantity', models.IntegerField(blank=True, verbose_name='Кол-во')),
                ('storage', models.CharField(blank=True, max_length=50, verbose_name='Где лежит')),
                ('price_purchasing', models.IntegerField(blank=True, verbose_name='Цена закупочная')),
                ('price_retail', models.IntegerField(blank=True, verbose_name='Цена розница')),
                ('price_wholesale', models.IntegerField(blank=True, verbose_name='Цена оптовая')),
                ('price_agent', models.IntegerField(blank=True, verbose_name='Цена cвоим')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.products')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='Имя')),
                ('balance', models.CharField(blank=True, max_length=40, verbose_name='Баланс')),
                ('status', models.CharField(blank=True, max_length=40, verbose_name='Статус')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.profile'),
        ),
        migrations.CreateModel(
            name='Markups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Название наценки')),
                ('price_range_from', models.IntegerField(blank=True, verbose_name='Диапазон цен от')),
                ('price_range_to', models.IntegerField(blank=True, verbose_name='Диапазон цен до')),
                ('markup', models.IntegerField(blank=True, verbose_name='Наценка')),
                ('markup_method', models.CharField(blank=True, max_length=20, verbose_name='Способ наценки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markups', to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=35, verbose_name='Имя')),
                ('post', models.CharField(blank=True, max_length=35, verbose_name='Должность')),
                ('status', models.IntegerField(blank=True, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(blank=True, max_length=40, verbose_name='Здание')),
                ('level', models.CharField(blank=True, max_length=40, verbose_name='Этаж')),
                ('line', models.CharField(blank=True, max_length=40, verbose_name='Линия')),
                ('department', models.CharField(blank=True, max_length=40, verbose_name='Отдел')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, verbose_name='Дата-время')),
                ('photo', models.ImageField(upload_to=main.models.sale_photo_save, verbose_name='Фото')),
                ('name', models.CharField(blank=True, max_length=175, verbose_name='Название')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('size', models.CharField(blank=True, max_length=30, verbose_name='Размер')),
                ('quantity', models.IntegerField(blank=True, verbose_name='Кол-во')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('sale_sum', models.IntegerField(blank=True, verbose_name='Сумма')),
                ('employer', models.CharField(blank=True, max_length=50, verbose_name='Сотрудник')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, verbose_name='Дата-время')),
                ('photo', models.ImageField(upload_to=main.models.sale_photo_save, verbose_name='Фото')),
                ('name', models.CharField(blank=True, max_length=175, verbose_name='Название')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('size', models.CharField(blank=True, max_length=30, verbose_name='Размер')),
                ('quantity', models.IntegerField(blank=True, verbose_name='Кол-во')),
                ('price', models.IntegerField(blank=True, verbose_name='Цена')),
                ('sale_sum', models.IntegerField(blank=True, verbose_name='Сумма')),
                ('employer', models.CharField(blank=True, max_length=50, verbose_name='Сотрудник')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='main.profile')),
            ],
        ),
    ]
