# Generated by Django 5.0.2 on 2024-03-17 20:54

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Photos',
        ),
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='main.profile'),
        ),
        migrations.AlterField(
            model_name='returns',
            name='photo',
            field=models.ImageField(upload_to=main.models.return_photo_save, verbose_name='Фото'),
        ),
    ]
